//Improve level
cout << "                      ____..." << endl;
cout << "             .-\"--\"\"\"\".__    `." << endl;
cout << "            |            `    |" << endl;
cout << "  (         `._....------.._.:" << endl;
cout << "   )         .()''        ``()." << endl;
cout << "  '          () .=='  `===  `-." << endl;
cout << "   . )       (   O      g)" << endl;
cout << "    )         )     /        J" << endl;
cout << "   (          |.   /      . (" << endl;
cout << "   $$         (.  (_'.   , )|`" << endl;
cout << "   ||         |\\`-....--'/  ' \\" << endl;
cout << "  /||.         \\\\ | | | /  /   \\." << endl;
cout << " //||(\\         \\`-===-'  '     \\o." << endl;
cout << ".//7' |)         `. --   / (     OObaaaad888b." << endl;
cout << "(<<. / |     .a888b`.__.'d\\     OO888888888888a." << endl;
cout << " \\  Y' |    .8888888aaaa88POOOOOO888888888888888." << endl;
cout << "  \\  \\ |   .888888888888888888888888888888888888b" << endl;
cout << "   |   |  .d88888P88888888888888888888888b8888888." << endl;
cout << "   b.--d .d88888P8888888888888888a:f888888|888888b" << endl;
cout << "   88888b 888888|8888888888888888888888888\\8888888" << endl;
cout << " ----------------------------------------------------------" << endl;
cout << "|         Yo, what's up? Wanna upgrade your weapon?        |"<<endl;
cout << "|     Gotta see if you've got the skills and the dough.    |"<<endl;
cout << "|     That'll cost ya 30kg of the shiny gold per level.    |"<<endl;
cout << "|      If you can't afford, don't waste my smoke time.     |"<<endl;
cout << " ----------------------------------------------------------"<<endl;

//gold
cout << "                           \\\|||///" << endl;
cout << "                         .  =======" << endl;
cout << "                        / \\| O   O |" << endl;
cout << "                        \\ / \\`___'/" << endl;
cout << "                         #   _| |_" << endl;
cout << "                        (#) (     )" << endl;
cout << "                         #\\//|* *|\\" << endl;
cout << "                         #\\/(  *  )/" << endl;
cout << "                         #   =====" << endl;
cout << "                         #   ( U )" << endl;
cout << "                         #   || ||" << endl;
cout << ".                        #---'| |`----." << endl;
cout << "                        `#----' `-----'" << endl;
cout << " ---------------------------------------------------------------" << endl;
cout << "|                      Oh! My dear owner,                       |"<<endl;
cout << "|        I've been waiting for you here for a long time!        |"<<endl;
cout << "|  The gold mine seems to have brightened up with your arrival. |"<<endl;
cout << "|             I'll lead the way for you right away.             |"<<endl;
cout << " ---------------------------------------------------------------"<<endl;

//member
cout << "            _...._" << endl;
cout << "        _.dMMMMMMMMMb." << endl;
cout << "    ..dMMMMMMMMMMMMMMMb" << endl;
cout << "  .dMMMMMMMMMMMMMMMMMMMMb." << endl;
cout << " dMMMMMMMMMMMMMMMMMMMMMMMM." << endl;
cout << " MMMMMMMP'`YMMMMMMMMMMMMMMMb" << endl;
cout << " MMMMMMP    MMMMMMMMMMMMMMMM" << endl;
cout << "dMMMMMP     `MMMMMMMMMMMMMMMb" << endl;
cout << "MMMMMM~=,,_  `MMMMMMMMMMMMMMM" << endl;
cout << "MMMMMMP,6;    `MMMMMMMMMMMMMMb" << endl;
cout << "MMMMMM|         ```^YMMMMMMMMM" << endl;
cout << "MMMMMM:   -~        / |MMMMMMMb" << endl;
cout << "`MMMMM/\\  _.._     /  |MMMMMMMM" << endl;
cout << "  `YMM\\_`.`~--'    \\__/MMMMMMMM!" << endl;
cout << "    MMMMMM\\       _.' _sS}MMMMMb" << endl;
cout << "    `YMMMMMb.__.sP.---.  MMMMMMM" << endl;
cout << "      ``YMMMMMMMP'        \\MMMMMb" << endl;
cout << "          ``MMMd;          MMMMMM" << endl;
cout << "              dP|          :MMMMMb." << endl;
cout << "          _.s88P'           :MMMMMM" << endl;
cout << "      _.s888888P',          |MMMMM}" << endl;
cout << " ---------------------------------------" << endl;
cout << "|    Hey! Come to hire someone, huh?    |"<<endl;
cout << "|       Is the pay sweet enough?        |"<<endl;
cout << "|  I'll pick some capable ones for you  |"<<endl;
cout << " ---------------------------------------"<<endl;

//crop
cout << "                     ___," << endl;
cout << "                  __)____)__)" << endl;
cout << "                    -)- )))" << endl;
cout << "            ,       \\=_/ \\__" << endl;
cout << "         __/).          )_/=\\" << endl;
cout << "        /6)   \\      __((_\\__\\" << endl;
cout << "       /   __/ \\    /_/-\\o____)" << endl;
cout << "      / ,_/|    \\   \\/  ))\\\\\\\\" << endl;
cout << "      \\_)o_'     _.-'  ,/:_/_\\\\    ___" << endl;
cout << "           '---`' \\>__/   /\\\\---.,/_  \\" << endl;
cout << "           (      /  /  /\\\\        \\)  \\" << endl;
cout << "           |        ('  \\\\\\        (   /" << endl;
cout << "      _____/         )__\\\\ /       /\\ (" << endl;
cout << "     /_______/,_____| |_,(       /  ) )" << endl;
cout << "    / (_     \\  |   _/ o)  \\     /_  |/" << endl;
cout << "    \\_ /     ( '| (___/     `.__  /  '" << endl;
cout << "              \\ |        / _/ / _/" << endl;
cout << "               \\(       / /  / /" << endl;
cout << "                )\\     / (  ( <" << endl;
cout << "             ,./_(,, ,/_|    \\_/,,._" << endl;
cout << " ----------------------------------------------------" << endl;
cout << "|   Come to the farm and wander around by yourself.  |"<<endl;
cout << "|    Take whatever fruits and veggies you fancy.     |"<<endl;
cout << "|                  I'm outta here.                   |"<<endl;
cout << " ----------------------------------------------------"<<endl;

//search
cout << "         .                  .-.    .  _   *     _   .\n";
cout << "                *          /   \\     ((       _/ \\       *\n";
cout << "              _    .   .--'\\/\\_ \\     `      /    \\  *    ___\n";
cout << "          *  / \\_    _/ ^      \\/\\'__        /\\/\\  /\\  __/   \\ *\n";
cout << "            /    \\  /    .'   _/  /  \\  *' /    \\/  \\/ .`'\\_/\\   .\n";
cout << "       .   /\\/\\/\\/ :' __  ^/  ^/    `--./.'  ^  `-.\\ _    _:\\ _\n";
cout << "          /    \\/  \\  _/  \\-' __/.' ^ _   \\_   .'\\   _/ \\ .  __/ \\\n";
cout << "        /\\  .-   `. \\/     \\ / -.   _/ \\ -. `_/   \\ /    `._/  ^  \\\n";
cout << "       /  `-.__ ^   / .-'.--'    . /    `--./ .-'  `-.  `-. `.  -  `.\n";
cout << "      /        `.  / /      `-.   /  .-'   / .   .'   \\    \\  \\  .-  \\\n";
cout << " -------------------------------------------------------------------------------" << endl;
cout << "|  Step into this land, and ahead lies the mysterious and uncharted territory,  |"<<endl;
cout << "|              fraught with perils yet hiding endless treasures,                |"<<endl;
cout << "|             where high risks and high rewards go hand in hand ~               |"<<endl;
cout << " -------------------------------------------------------------------------------"<<endl;
